name: tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  oapi-cli-tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependancies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y -f -o Acquire::Retries=3 jq libjson-c-dev libcurl4-openssl-dev pkg-config cargo
    - name: tests
      run: ./scripts/oapi-cli-tests.sh