name: tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  oapi-cli-tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: install dependancies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y -f -o Acquire::Retries=3 jq libjson-c-dev libcurl4-openssl-dev pkg-config cargo
    - name: oapi-cli local tests 
      run: ./scripts/oapi-cli-tests.sh
  osc-cli-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: osc-cli local tests
      run: ./scripts/osc-cli-tests.sh
  osc-sdk-c-tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: install dependancies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y -f -o Acquire::Retries=3 jq libjson-c-dev libcurl4-openssl-dev pkg-config libjsoncpp-dev
    - name: osc-sdk-c local tests
      run: ./scripts/osc-sdk-c-tests.sh
  osc-sdk-go-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: osc-sdk-go local tests
        run: ./scripts/osc-sdk-go-tests.sh
  osc-sdk-python-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: osc-sdk-python local tests
      run: ./scripts/osc-sdk-python-tests.sh
  osc-sdk-rust-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Stable Rust with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        components: rustfmt
    - name: osc-sdk-rust local tests
      run: ./scripts/osc-sdk-rust-tests.sh
  osc-sdk-js-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 20.5.1
    - name: make nvm available
      run: |
        sudo cp ~/.nvm/nvm.sh /usr/local/bin/nvm
        sudo chmod +x /usr/local/bin/nvm
    - name: osc-sdk-js local tests
      run: ./scripts/osc-sdk-js-tests.sh
  osc-sdk-java-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: outscale/osc-sdk-java
          path: osc-sdk-java
      - name: Copy xml Java setup
        run: |
          sudo cp osc-sdk-java/pom.xml .
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '11'
          cache: 'maven'
      - name: osc-sdk-java local tests
        run: ./scripts/osc-sdk-java-tests.sh